### ISSUE TITLE
certain article sont pas lu en mode show

### ISSUE THREAD

**Issue by tchret** [tchret/thefreshest#46]
![image](https://cloud.githubusercontent.com/assets/4539476/7668368/efd51d42-fc34-11e4-8682-cd2eaffe4570.png)

on obtient juste `...` 

marche pas pour
- medium 
- entrepreneur
- fast company

marche pour 
- techcrunch
- entrepreneur
- HVBR

**Comment by tchret** [comment]
@Eschults ce qu'on peut faire c'est prendre le contenu de la description de la page if `...`, tout simplement

**Comment by Eschults** [comment]
ouais j'avoue j'ai fait de la merde, en fait j'avais remarqué que yavait
des articles ou yavait pas de "content" dans le meta, et je trouvais ça
dommage, donc je me suis dit on va scraper à la mano et récupérer le
premier paragraphe, mais c'était évident que selon les sources, la classe
de la div de l'article serait pas la même, je devais être un peu fatigué...
il faut qu'on discute de toute façon, à la limite demain matin 9h café ?

2015-05-17 1:44 GMT+02:00 Thomas Chrétien <notifications@github.com>:
