### ISSUE TITLE
"too many redirects "

### ISSUE THREAD

**Issue by tchret** [tchret/thefreshest#48]
sale erreur sur l'index

`FaradayMiddleware::RedirectLimitReached `
```
too many redirects; last one to: https://hbr.org/2015/05/apple-spotify-and-the-battle-over-freemium-2?utm_source=Socialflow&utm_medium=Tweet&utm_campaign=Socialflow
```

**Comment by tchret** [comment]
http://www.rubydoc.info/gems/agiley-faraday_middleware/FaradayMiddleware/RedirectLimitReached

**Comment by tchret** [comment]
Le problème surgit lors du `MetaInspector.new(lien)` avec ce lien : 
```
lien = https://hbr.org/2015/05/apple-spotify-and-the-battle-over-freemium-2?utm_source=Socialflow&utm_medium=Tweet&utm_campaign=Socialflow 
```

**Comment by Eschults** [comment]
Ouais c'est horrible, ça vient de la gem. On lui met une issue ? :)
