### ISSUE TITLE
détecter si l'influencer a un tweet épinglé...

### ISSUE THREAD

**Issue by tchret** [tchret/thefreshest#7]
... et prendre le suivant si c'est le cas !! :)

**Comment by Eschults** [comment]
bien vuuuuu
ca se détecte facilement ça ?
ça me fait penser que c'est ça que j'avais mis dans le premier schema de données qui a disparu : ```published_at```

**Comment by tchret** [comment]
yes t'as une classe `is pinned`, je suis dessus
